import React from "react";
import Head from "next/head";
import classNames from "classnames";
import styles from "./billing.module.scss";
import Appbar from "../components/Appbar/Appbar";
import Stepper from "../components/Stepper/Stepper";
import FormField from "../components/FormField/FormField";
import Button from "../components/Button/Button";
import Footer from "../components/Footer/Footer";

export default function Billing() {
  return (
    <div className={classNames(styles.billing)}>
      <Head>
        <title>FruigeBag, buy fresh fruits and vegetables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* Appbar */}
        <Appbar customClasses={classNames(styles.billing__header)} logo />
        {/* Stepper */}
        <Stepper
          step1
          step2
          step3
          customClasses={classNames(styles.billing__stepper)}
        />
        <main className="billing__main">
          <form className={classNames(styles.billing__form, "form")}>
            <div className="form__section">
              <h1 className="form__title">Billing Address</h1>
            </div>
            <div className="form__section">
              {/* Full Name */}
              <FormField
                type="text"
                id="full_name"
                name="full_name"
                label="Full Name"
              />
            </div>
            <div className="form__section">
              {/* Address */}
              <FormField
                type="text"
                id="address"
                name="address"
                label="Address"
              />
            </div>
            <div className="form__section">
              {/* City */}
              <FormField type="text" id="city" name="city" label="City" />
            </div>
            <div className="form__section">
              {/* Postal Code */}
              <FormField
                type="text"
                id="postal_code"
                name="postal_code"
                label="Postal Code"
              />
            </div>
            <div className="form__section">
              {/* Country */}
              <FormField
                type="text"
                id="country"
                name="country"
                label="Country"
              />
            </div>
            <div className="form__section">
              <Button url="/payment" primary link customClasses="form__btn">
                Continue
              </Button>
            </div>
          </form>
        </main>
      </div>
      {/* Footer */}
      <Footer mini customClasses={styles.billing__footer} />
    </div>
  );
}
