import React from "react";
import { useSelector } from "react-redux";
import Head from "next/head";
import { selectFavoriteProducts } from "../state/features/favorite/favoriteSlice";
import classNames from "classnames";
import styles from "./favorite.module.scss";
import Appbar from "../components/Appbar/Appbar";
import NewsLetter from "../components/NewsLetter/NewsLetter";
import Footer from "../components/Footer/Footer";
import ProductCard from "../components/ProductCard/ProductCard";

export default function Favorite({}) {
  const favoriteProducts = useSelector(selectFavoriteProducts);
  const renderedFavoriteProducts = favoriteProducts.map((product) => {
    return <ProductCard key={product.id} product={product} />;
  });

  return (
    <div className={classNames(styles.favorite)}>
      <Head>
        <title>FruigeBag, buy fresh fruits and vegetables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* Appbar */}
        <Appbar
          customClasses={classNames(styles.favorite__header)}
          logo
          search
          nav
        />
        <main className={classNames(styles.favorite__main, "section")}>
          <div className={classNames(styles.favorite__grid)}>
            {renderedFavoriteProducts}
          </div>
        </main>
      </div>
      {/* NewsLetter */}
      <NewsLetter />
      {/* Footer */}
      <Footer customClasses={styles.favorite__footer} />
    </div>
  );
}
