import Head from "next/head";
import classNames from "classnames";
import styles from "./Home.module.scss";
import Appbar from "../components/Appbar/Appbar";
import Hero from "../components/Hero/Hero";
import Featured from "../components/Featured/Featured";
import Products from "../components/Products/Products";
import NewsLetter from "../components/NewsLetter/NewsLetter";
import Footer from "../components/Footer/Footer";
import { featuredData, productsData } from "../data/data";
import { getProducts } from "../services/products";

export default function Home({ products }) {
  return (
    <div className={classNames(styles.home)}>
      <Head>
        <title>FruigeBag, buy fresh fruits and vegetables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* Appbar */}
        <Appbar
          customClasses={classNames(styles.home__header)}
          logo
          nav
          search
        />
      </div>

      <main className={classNames(styles.home__main)}>
        <div className="container">
          {/* Hero */}
          <Hero customClasses="home__hero section" />

          {/* Featured */}
          <Featured
            customClasses="home__featured section"
            featuredData={featuredData}
          />

          {/* Products */}
          <Products
            customClasses="home__products section"
            products={products}
          />
        </div>
        {/* NewsLetter */}
        <NewsLetter customClasses="home__newsletter" />
      </main>

      {/* Footer */}
      <Footer customClasses="home__footer" />
    </div>
  );
}

export const getServerSideProps = async () => {
  const products = getProducts();
  return {
    props: {
      products: products,
    },
  };
};
