import React from "react";
import { useRouter } from "next/router";
import { useDispatch, useSelector } from "react-redux";
import Head from "next/head";
import classNames from "classnames";
import styles from "./payment.module.scss";
import Appbar from "../components/Appbar/Appbar";
import Stepper from "../components/Stepper/Stepper";
import Button from "../components/Button/Button";
import Footer from "../components/Footer/Footer";
import Radio from "../components/Radio/Radio";

import { addPaymentMethod } from "../state/features/order/orderSlice";

export default function Payment() {
  const paymentMethod = useSelector((state) => state.order.paymentMethod);
  const dispatch = useDispatch();

  const router = useRouter();

  // TODO: use router effect to check billing info

  const handleSubmit = async (evt) => {
    evt.preventDefault();

    dispatch(addPaymentMethod(paymentMethod));
    router.push("/placeOrder");
  };

  return (
    <div className={classNames(styles.payment)}>
      <Head>
        <title>FruigeBag, buy fresh fruits and vegetables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* Appbar */}
        <Appbar customClasses={classNames(styles.payment__header)} logo />
        {/* Stepper */}
        <Stepper
          step1
          step2
          step3
          step4
          customClasses={classNames(styles.payment__stepper)}
        />
        <main className="payment__main">
          <form
            className={classNames(styles.payment__form, "form")}
            onSubmit={handleSubmit}
          >
            <div className="form__section">
              <h1 className="form__title">Payment Method</h1>
            </div>
            <div className="form__section">{/* PayPal */}</div>

            <div className="form__section">
              <Radio
                id="payment_method_paypal"
                name="payment_method"
                label="PayPal"
                value="paypal"
                disabled={true}
              />
            </div>
            <div className="form__section">
              <Radio
                id="payment_method_credit"
                name="payment_method"
                label="Credit Card"
                value="credit"
              />
            </div>
            <div className="form__section">
              <Button primary customClasses="form__btn">
                Continue
              </Button>
            </div>
          </form>
        </main>
      </div>
      {/* Footer */}
      <Footer mini customClasses={styles.payment__footer} />
    </div>
  );
}
