import React from "react";
import Head from "next/head";
import classNames from "classnames";
import styles from "./placeOrder.module.scss";
import Appbar from "../components/Appbar/Appbar";
import Stepper from "../components/Stepper/Stepper";
import SummaryCard from "../components/SummaryCard/SummaryCard";
import PlaceOrderCard from "../components/PlaceOrderCard/PlaceOrderCard";
import Footer from "../components/Footer/Footer";
import {
  shippingInfo,
  billingInfo,
  paymentInfo,
  itemsInfo,
} from "../data/data";

export default function PlaceOrder() {
  return (
    <div className={classNames(styles.placeOrder)}>
      <Head>
        <title>FruigeBag, buy fresh fruits and vegetables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* Appbar */}
        <Appbar customClasses={classNames(styles.placeOrder__header)} logo />
        {/* Stepper */}
        <Stepper
          step1
          step2
          step3
          step4
          step5
          customClasses={classNames(styles.placeOrder__stepper)}
        />
        <main className={classNames(styles.placeOrder__main, "section")}>
          <section className={classNames(styles.placeOrder__info)}>
            <div className={classNames(styles["placeOrder__info-sect"])}>
              <PlaceOrderCard shipping info={shippingInfo} />
            </div>
            <div className={classNames(styles["placeOrder__info-sect"])}>
              <PlaceOrderCard billing info={billingInfo} />
            </div>
            <div className={classNames(styles["placeOrder__info-sect"])}>
              <PlaceOrderCard payment info={paymentInfo} />
            </div>
            <div className={classNames(styles["placeOrder__info-sect"])}>
              <PlaceOrderCard items info={shippingInfo} />
            </div>
          </section>
          <section className={classNames(styles.placeOrder__sumary)}>
            <SummaryCard
              order={{
                title: "Order Summary",
                itemsNum: 2,
                itemsPrice: 5,
                shipping: 3,
                tax: 1,
                total: 9,
              }}
            />
          </section>
        </main>
      </div>
      {/* Footer */}
      <Footer mini customClasses={styles.placeOrder__footer} />
    </div>
  );
}
