import React from "react";
import { useSelector } from "react-redux";
import Head from "next/head";
import classNames from "classnames";
import styles from "./placeOrder.module.scss";
import Appbar from "../components/Appbar/Appbar";
import Stepper from "../components/Stepper/Stepper";
import PlaceOrderSummary from "../components/SummaryCard/PlaceOrderSummary";
import PlaceOrderShippingCard from "../components/PlaceOrderCard/PlaceOrderShippingCard";
import PlaceOrderBillingCard from "../components/PlaceOrderCard/PlaceOrderBillingCard";
import PlaceOrderPaymentCard from "../components/PlaceOrderCard/PlaceOrderPaymentCard";
import PlaceOrderItemsCard from "../components/PlaceOrderCard/PlaceOrderItemsCard";
import Footer from "../components/Footer/Footer";
import { selectCartProducts } from "../state/features/cart/cartSlice";
import { useSummary } from "../hooks/summary";

export default function PlaceOrder() {
  const { shipping, billing, paymentMethod } = useSelector(
    (state) => state.order
  );

  const cartProducts = useSelector(selectCartProducts);

  const order = {
    shipping,
    billing,
    paymentMethod,
    items: cartProducts,
  };

  const summary = useSummary();

  return (
    <div className={classNames(styles.placeOrder)}>
      <Head>
        <title>FruigeBag, buy fresh fruits and vegetables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* Appbar */}
        <Appbar customClasses={classNames(styles.placeOrder__header)} logo />
        {/* Stepper */}
        <Stepper
          step1
          step2
          step3
          step4
          step5
          customClasses={classNames(styles.placeOrder__stepper)}
        />
        <main className={classNames(styles.placeOrder__main, "section")}>
          <section className={classNames(styles.placeOrder__info)}>
            <div className={classNames(styles["placeOrder__info-sect"])}>
              <PlaceOrderShippingCard shippingInfo={shipping} />
            </div>
            <div className={classNames(styles["placeOrder__info-sect"])}>
              <PlaceOrderBillingCard billingInfo={billing} />
            </div>
            <div className={classNames(styles["placeOrder__info-sect"])}>
              <PlaceOrderPaymentCard paymentMethod={paymentMethod} />
            </div>
            <div className={classNames(styles["placeOrder__info-sect"])}>
              <PlaceOrderItemsCard itemsInfo={cartProducts} />
            </div>
          </section>
          <section className={classNames(styles.placeOrder__sumary)}>
            <PlaceOrderSummary order={order} summary={summary} />
          </section>
        </main>
      </div>
      {/* Footer */}
      <Footer mini customClasses={styles.placeOrder__footer} />
    </div>
  );
}
