import React from "react";
import Head from "next/head";
import Link from "next/link";
import classNames from "classnames";
import styles from "./profile.module.scss";
import Appbar from "../components/Appbar/Appbar";
import FormField from "../components/FormField/FormField";
import Button from "../components/Button/Button";
import Footer from "../components/Footer/Footer";

export default function profile() {
  return (
    <div className={classNames(styles.profile)}>
      <Head>
        <title>FruigeBag, buy fresh fruits and vegetables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* Appbar */}
        <Appbar
          customClasses={classNames(styles.profile__header)}
          logo
          search
          nav
        />
        <main className="profile__main">
          <form className={classNames(styles.profile__form, "form")}>
            <div className="form__section">
              <h1 className="form__title">My Account</h1>
            </div>
            <div className="form__section">
              <p className="form__auth">
                <span className="form__auth-text">
                  Update your account information
                </span>
              </p>
            </div>
            <div className="form__section">
              {/* Username */}
              <FormField
                type="text"
                id="username"
                name="username"
                label="Username"
              />
            </div>
            <div className="form__section">
              {/* Email */}
              <FormField type="text" id="email" name="email" label="Email" />
            </div>
            <div className="form__section">
              {/* Password */}
              <FormField
                type="password"
                id="password"
                name="password"
                label="Password"
              />
            </div>
            <div className="form__section">
              {/* Confirm Password */}
              <FormField
                type="password"
                id="passwordConfirm"
                name="passwordConfirm"
                label="Confirm Password"
              />
            </div>
            <div className="form__section">
              <Button primary customClasses="form__btn">
                Update
              </Button>
            </div>
            <div className="form__section">
              <Button secondary outline customClasses="form__btn">
                Delete
              </Button>
            </div>
          </form>
        </main>
      </div>
      {/* Footer */}
      <Footer mini customClasses={styles.profile__footer} />
    </div>
  );
}
