import React, { useState } from "react";
import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import classNames from "classnames";
import styles from "./register.module.scss";
import Appbar from "../components/Appbar/Appbar";
import FormField from "../components/FormField/FormField";
import Button from "../components/Button/Button";
import Footer from "../components/Footer/Footer";

import { hasError } from "../utils/form";

export default function Register(props) {
  // input state
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [passwordConfirm, setPasswordConfirm] = useState("");

  // errors state
  const [usernameError, setUsernameError] = useState("");
  const [emailError, setEmailError] = useState("");
  const [passwordError, setPasswordError] = useState("");
  const [passwordConfirmError, setPasswordConfirmError] = useState("");

  const handleSubmit = async (evt) => {
    evt.preventDefault();
    const { data } = await axios.post("/api/users/register", {
      data: {
        username,
        email,
        password,
        passwordConfirm,
      },
    });

    // console.log(data);

    if (hasError(data)) {
      // console.log("Has errors");
      resetErrors();
      handleErrors(data["errors"]);
    } else {
      resetErrors();
      alert("Register successfully");
    }
  };

  /**
   * Reset error messages
   */
  const resetErrors = function () {
    setUsernameError("");
    setEmailError("");
    setPasswordError("");
    setPasswordConfirmError("");
  };

  /**
   * Extract errors
   */
  const handleErrors = function (errorsData) {
    errorsData.forEach((errorEntry) => {
      if (errorEntry.param === "data.username") {
        setUsernameError(errorEntry.msg);
      }
      if (errorEntry.param === "data.email") {
        setEmailError(errorEntry.msg);
      }
      if (errorEntry.param === "data.password") {
        setPasswordError(errorEntry.msg);
      }
      if (errorEntry.param === "data.passwordConfirm") {
        setPasswordConfirmError(errorEntry.msg);
      }
    });
  };

  return (
    <div className={classNames(styles.register)}>
      <Head>
        <title>FruigeBag, buy fresh fruits and vegetables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* Appbar */}
        <Appbar customClasses={classNames(styles.register__header)} logo />
        <main className="register__main">
          <form
            className={classNames(styles.register__form, "form")}
            onSubmit={handleSubmit}
          >
            <div className="form__section">
              <h1 className="form__title">Register to FruigeBag</h1>
            </div>
            <div className="form__section">
              <p className="form__auth">
                <span className="form__auth-text">
                  Already have an account?{" "}
                </span>
                <Link href="/login" passHref>
                  <a className="form__auth-link">Login</a>
                </Link>
              </p>
            </div>
            <div className="form__section">
              {/* Username */}
              <FormField
                type="text"
                id="username"
                name="username"
                label="Username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                errorMessage={usernameError}
              />
            </div>
            <div className="form__section">
              {/* Email */}
              <FormField
                type="text"
                id="email"
                name="email"
                label="Email"
                value={email}
                onChange={(e) => {
                  setEmail(e.target.value);
                }}
                errorMessage={emailError}
              />
            </div>
            <div className="form__section">
              {/* Password */}
              <FormField
                type="password"
                id="password"
                name="password"
                label="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                errorMessage={passwordError}
              />
            </div>
            <div className="form__section">
              {/* Confirm Password */}
              <FormField
                type="password"
                id="passwordConfirm"
                name="passwordConfirm"
                label="Confirm Password"
                value={passwordConfirm}
                onChange={(e) => setPasswordConfirm(e.target.value)}
                errorMessage={passwordConfirmError}
              />
            </div>
            <div className="form__section">
              <Button primary customClasses="form__btn">
                Register
              </Button>
            </div>
          </form>
        </main>
      </div>
      {/* Footer */}
      <Footer mini customClasses={styles.register__footer} />
    </div>
  );
}
