import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { useDispatch, useSelector } from "react-redux";
import Head from "next/head";
import classNames from "classnames";
import styles from "./shipping.module.scss";
import Appbar from "../components/Appbar/Appbar";
import Stepper from "../components/Stepper/Stepper";
import FormField from "../components/FormField/FormField";
import Checkbox from "../components/Checkbox/Checkbox";
import Button from "../components/Button/Button";
import Footer from "../components/Footer/Footer";

import { addShipping, addBilling } from "../state/features/order/orderSlice";

import {
  isValidFullName,
  isValidAddress,
  isValidCity,
  isValidPostalCode,
  isValidCountry,
} from "../utils/form";

export default function Shipping() {
  const shippingInfo = useSelector((state) => state.order.shipping);
  const dispatch = useDispatch();

  console.log(shippingInfo);
  console.log(shippingInfo.fillBilling);

  const [fullName, setFullName] = useState(shippingInfo.fullName);
  const [address, setAddress] = useState(shippingInfo.address);
  const [city, setCity] = useState(shippingInfo.city);
  const [postalCode, setPostalCode] = useState(shippingInfo.postalCode);
  const [country, setCountry] = useState(shippingInfo.country);
  const [billingCheck, setBillingCheck] = useState(shippingInfo.fillBilling);

  const [fullNameError, setFullNameError] = useState("");
  const [addressError, setAddressError] = useState("");
  const [cityError, setCityError] = useState("");
  const [postalCodeError, setPostalCodeError] = useState("");
  const [countryError, setCountryError] = useState("");

  const userInfo = true;
  const router = useRouter();

  useEffect(() => {
    if (!userInfo) {
      router.push("/login");
    }
  }, [userInfo, router]);

  const handleSubmit = async (evt) => {
    evt.preventDefault();

    handleErrorMessages("", "", "", "", "");

    const checkFullName = isValidFullName(fullName);
    const checkAddress = isValidAddress(address);
    const checkCity = isValidCity(city);
    const checkPostalCode = isValidPostalCode(postalCode);
    const checkCountry = isValidCountry(country);

    handleErrorMessages(
      checkFullName.errorMessage,
      checkAddress.errorMessage,
      checkCity.errorMessage,
      checkPostalCode.errorMessage,
      checkCountry.errorMessage
    );

    const validFields =
      checkFullName.answer &&
      checkAddress.answer &&
      checkCity.answer &&
      checkPostalCode.answer &&
      checkCountry.answer;

    if (validFields) {
      dispatch(
        addShipping({
          fullName,
          address,
          city,
          postalCode,
          country,
          billingCheck,
        })
      );

      // Billing is the same as shipping
      if (billingCheck) {
        dispatch(
          addBilling({
            fullName,
            address,
            city,
            postalCode,
            country,
          })
        );
      }
      router.push("/billing");
    }

    console.log(`validFields: ${checkCountry.answer}`);

    console.log("Shipping address submitted");
  };

  /**
   * Handle error messages
   * @param {string} fullNameMsg
   * @param {string} addressMsg
   * @param {string} cityMsg
   * @param {string} postalCodeMsg
   * @param {string} countryMsg
   */
  const handleErrorMessages = (
    fullNameMsg,
    addressMsg,
    cityMsg,
    postalCodeMsg,
    countryMsg
  ) => {
    setFullNameError(fullNameMsg);
    setAddressError(addressMsg);
    setCityError(cityMsg);
    setPostalCodeError(postalCodeMsg);
    setCountryError(countryMsg);
  };

  return (
    <div className={classNames(styles.shipping)}>
      <Head>
        <title>FruigeBag, buy fresh fruits and vegetables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* Appbar */}
        <Appbar customClasses={classNames(styles.shipping__header)} logo />
        {/* Stepper */}
        <Stepper
          step1
          step2
          customClasses={classNames(styles.shipping__stepper)}
        />
        <main className="shipping__main">
          <form
            className={classNames(styles.shipping__form, "form")}
            onSubmit={handleSubmit}
          >
            <div className="form__section">
              <h1 className="form__title">Shipping Address</h1>
            </div>
            <div className="form__section">
              {/* Full Name */}
              <FormField
                type="text"
                id="full_name"
                name="full_name"
                label="Full Name"
                value={fullName}
                onChange={(e) => setFullName(e.target.value)}
                errorMessage={fullNameError}
              />
            </div>
            <div className="form__section">
              {/* Address */}
              <FormField
                type="text"
                id="address"
                name="address"
                label="Address"
                value={address}
                onChange={(e) => setAddress(e.target.value)}
                errorMessage={addressError}
              />
            </div>
            <div className="form__section">
              {/* City */}
              <FormField
                type="text"
                id="city"
                name="city"
                label="City"
                value={city}
                onChange={(e) => setCity(e.target.value)}
                errorMessage={cityError}
              />
            </div>
            <div className="form__section">
              {/* Postal Code */}
              <FormField
                type="text"
                id="postal_code"
                name="postal_code"
                label="Postal Code"
                value={postalCode}
                onChange={(e) => setPostalCode(e.target.value)}
                errorMessage={postalCodeError}
              />
            </div>
            <div className="form__section">
              {/* Country */}
              <FormField
                type="text"
                id="country"
                name="country"
                label="Country"
                value={country}
                onChange={(e) => setCountry(e.target.value)}
                errorMessage={countryError}
              />
            </div>
            <div className="form__section">
              <Checkbox
                id="billing_checkbox"
                name="billing_checkbox"
                checked={billingCheck}
                label="My Billing address is the same as my Shipping address"
                onCheck={(evt) => {
                  setBillingCheck(!billingCheck);
                }}
              />
            </div>
            <div className="form__section">
              <Button primary customClasses="form__btn">
                Continue
              </Button>
            </div>
          </form>
        </main>
      </div>
      {/* Footer */}
      <Footer mini customClasses={styles.shipping__footer} />
    </div>
  );
}
